### PR TITLE
Added Basic Fortnite Model!

### PR DESCRIPTION
**Pull request by vanishLLC**
Credits goes to natdog400 who took data I trained and compiled it

### CODE REVIEW

**Comment by centerepic** [comment]
This is pretty cool! Seems like this tool might expand to be used on more than just Roblox.

**Comment by vanishLLC** [comment]
I personally lowered fov to 568 confidence 48 sensitivity 0.8

**Comment by vanishLLC** [comment]
I personally lowered fov to 568 confidence 48 sensitivity 0.8

**Comment by MarsQQ** [comment]
Looks amazing! Thank you for your contribution :D

**Comment by djpacker17** [comment]
crash ;c

**Pull request merged**
